select * from cust01;
-- 1) What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue
from cust01
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount
from cust01
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from cust01);

-- Q3. Which are the top 5 products with the highest average review rating?
select
    item_purchased,
    round(avg(review_rating), 2) as avg_rating
FROM cust01
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

select shipping_type, 
ROUND(AVG(purchase_amount),2) avg_p_ampount
from cust01
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status, 
count(customer_id) as total_customers,
round(sum(purchase_amount),2) as total_revenue,
round(avg(purchase_amount),2) as avg_revenue
from cust01
group by subscription_status
order by total_revenue,avg_revenue desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, round(100.0 * sum(case when discount_applied ='Yes' then 1 else 0 end)/ count(*),2) as disapplied
from cust01
group by item_purchased
order by disapplied desc;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
with ctype as 
(select customer_id , previous_purchases,
 case when previous_purchases = 1 then "New"
	  when previous_purchases between 4 and 10 then "Returning"
      else "Loyal"
 end as csegment 
 from cust01)
 select csegment, count(*) as  "Number of customer"
 from ctype
 group by csegment;
 
 -- Q8. What are the top 3 most purchased products within each category? 
 
with icount as (
select item_purchased,category, 
 count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as irank
from cust01
group by  category, item_purchased
)
select item_purchased, category , total_orders
from icount
where irank = 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select  count(customer_id) as rep_buyers, subscription_status
from cust01
where  previous_purchases> 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group? 
select sum(purchase_amount) total_revenue, age_group
from cust01
group by age_group
order by total_revenue desc;

-- Q11 Which are the top 10 cities for generating revenue?
select sum(purchase_amount) total_revenue, location
from cust01
group by location
order by total_revenue desc
limit 10;

-- Q12 What is the total revenue based on season ?
select season,sum(purchase_amount) total_revenue
from cust01
group by season
order by total_revenue desc;